# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medicine_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 921)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #f0f4f8;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.medicineGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.medicineGroupBox.setGeometry(QtCore.QRect(0, 0, 1111, 991))
        self.medicineGroupBox.setStyleSheet("QGroupBox {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"")
        self.medicineGroupBox.setObjectName("medicineGroupBox")
        self.Medicinename = QtWidgets.QLabel(self.medicineGroupBox)
        self.Medicinename.setGeometry(QtCore.QRect(10, 80, 161, 21))
        self.Medicinename.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 11pt;\n"
"    color: #333333;\n"
"}\n"
"")
        self.Medicinename.setObjectName("Medicinename")
        self.label_2 = QtWidgets.QLabel(self.medicineGroupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 131, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 11pt;\n"
"    color: #333333;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.medicineGroupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 131, 21))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 11pt;\n"
"    color: #333333;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.medicineGroupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 81, 21))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 11pt;\n"
"    color: #333333;\n"
"}\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.nameInput = QtWidgets.QLineEdit(self.medicineGroupBox)
        self.nameInput.setGeometry(QtCore.QRect(170, 80, 113, 31))
        self.nameInput.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    background-color: #f5faff;\n"
"}\n"
"")
        self.nameInput.setObjectName("nameInput")
        self.expiryInput = QtWidgets.QLineEdit(self.medicineGroupBox)
        self.expiryInput.setGeometry(QtCore.QRect(170, 150, 113, 31))
        self.expiryInput.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    background-color: #f5faff;\n"
"}\n"
"")
        self.expiryInput.setObjectName("expiryInput")
        self.userIdInput = QtWidgets.QLineEdit(self.medicineGroupBox)
        self.userIdInput.setGeometry(QtCore.QRect(170, 330, 113, 31))
        self.userIdInput.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    background-color: #f5faff;\n"
"}\n"
"")
        self.userIdInput.setObjectName("userIdInput")
        self.countInput = QtWidgets.QLineEdit(self.medicineGroupBox)
        self.countInput.setGeometry(QtCore.QRect(170, 240, 111, 31))
        self.countInput.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    background-color: #f5faff;\n"
"}\n"
"")
        self.countInput.setObjectName("countInput")
        self.addButton = QtWidgets.QPushButton(self.medicineGroupBox)
        self.addButton.setGeometry(QtCore.QRect(10, 420, 111, 28))
        self.addButton.setStyleSheet("QPushButton {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 6px 12px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.addButton.setObjectName("addButton")
        self.showBlocksButton = QtWidgets.QPushButton(self.medicineGroupBox)
        self.showBlocksButton.setGeometry(QtCore.QRect(10, 490, 131, 28))
        self.showBlocksButton.setStyleSheet("QPushButton {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 6px 12px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"\n"
"")
        self.showBlocksButton.setObjectName("showBlocksButton")
        self.StatusLabel = QtWidgets.QLabel(self.medicineGroupBox)
        self.StatusLabel.setGeometry(QtCore.QRect(0, 560, 311, 61))
        self.StatusLabel.setStyleSheet("QLabel#StatusLabel {\n"
"    color: green;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"    padding: 4px;\n"
"}\n"
"")
        self.StatusLabel.setText("")
        self.StatusLabel.setObjectName("StatusLabel")
        self.blockDisplay = QtWidgets.QTextBrowser(self.medicineGroupBox)
        self.blockDisplay.setGeometry(QtCore.QRect(430, 40, 641, 731))
        self.blockDisplay.setStyleSheet("QTextBrowser {\n"
"    background-color: #f0f0f0;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: Consolas, monospace;\n"
"}\n"
"\n"
"")
        self.blockDisplay.setObjectName("blockDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.medicineGroupBox.setTitle(_translate("MainWindow", "Medicine Info"))
        self.Medicinename.setText(_translate("MainWindow", "Medicine Name"))
        self.label_2.setText(_translate("MainWindow", "Expiration Date"))
        self.label_3.setText(_translate("MainWindow", "Medicine Count"))
        self.label_4.setText(_translate("MainWindow", "User ID"))
        self.addButton.setText(_translate("MainWindow", "PushButton"))
        self.showBlocksButton.setText(_translate("MainWindow", "Show Blockchain"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
